
import { Doctor } from '@/types';

export const MOCK_DOCTORS: Doctor[] = [
  {
    id: '1',
    name: 'Dra. Elena Martínez',
    specialty: 'Psicólogo',
    location: 'Madrid',
    city: 'Madrid',
    rating: 4.9,
    reviewCount: 124,
    priceRange: '60€ - 90€',
    image: 'https://picsum.photos/seed/doctor1/200/200',
    insurances: ['Sanitas', 'Adeslas', 'Mapfre'],
    bio: 'Especialista en terapia cognitivo-conductual con más de 10 años de experiencia tratando ansiedad y depresión.',
    availability: ['2024-06-10T09:00:00', '2024-06-10T11:00:00', '2024-06-11T16:00:00'],
    isVerified: true,
    address: 'Calle Velázquez, 45, 2º Izq, Madrid'
  },
  {
    id: '2',
    name: 'Dr. Javier Ruiz',
    specialty: 'Dermatólogo',
    location: 'Barcelona',
    city: 'Barcelona',
    rating: 4.7,
    reviewCount: 89,
    priceRange: '80€ - 120€',
    image: 'https://picsum.photos/seed/doctor2/200/200',
    insurances: ['Sanitas', 'Asisa'],
    bio: 'Experto en dermatología estética y oncología cutánea. Miembro de la Academia Española de Dermatología.',
    availability: ['2024-06-10T10:30:00', '2024-06-12T09:00:00'],
    isVerified: true,
    address: 'Carrer de Balmes, 129, Barcelona'
  },
  {
    id: '3',
    name: 'Dra. Sofía Castro',
    specialty: 'Ginecólogo',
    location: 'Valencia',
    city: 'Valencia',
    rating: 4.9,
    reviewCount: 210,
    priceRange: '50€ - 100€',
    image: 'https://picsum.photos/seed/doctor3/200/200',
    insurances: ['Adeslas', 'DKV', 'Caser'],
    bio: 'Atención integral a la mujer en todas las etapas de la vida. Control de embarazo de alto riesgo.',
    availability: ['2024-06-10T08:00:00', '2024-06-10T13:00:00', '2024-06-13T10:00:00'],
    isVerified: true,
    address: 'Avenida de las Cortes Valencianas, 58, Valencia'
  },
  {
    id: '4',
    name: 'Dr. Miguel Ángel Torres',
    specialty: 'Pediatra',
    location: 'Madrid',
    city: 'Madrid',
    rating: 4.8,
    reviewCount: 156,
    priceRange: '70€ - 110€',
    image: 'https://picsum.photos/seed/doctor4/200/200',
    insurances: ['Sanitas', 'Mapfre'],
    bio: 'Especialista en pediatría y puericultura. Seguimiento del desarrollo infantil y vacunación.',
    availability: ['2024-06-14T09:00:00', '2024-06-14T12:00:00'],
    isVerified: false,
    address: 'Paseo de la Castellana, 12, Madrid'
  }
];

export const SPECIALTIES = [
  // Especialidades médicas principales
  'Alergología',
  'Anestesiología',
  'Angiología y Cirugía Vascular',
  'Cardiología',
  'Cirugía General',
  'Cirugía Cardiovascular',
  'Cirugía Maxilofacial',
  'Cirugía Pediátrica',
  'Cirugía Plástica',
  'Cirugía Torácica',
  'Dermatología',
  'Endocrinología',
  'Endoscopia',
  'Fisioterapia',
  'Gastroenterología',
  'Geriatría',
  'Ginecología y Obstetricia',
  'Hematología',
  'Hepatología',
  'Infectología',
  'Inmunología',
  'Medicina de Urgencias',
  'Medicina del Deporte',
  'Medicina del Trabajo',
  'Medicina Estética',
  'Medicina Familiar',
  'Medicina General',
  'Medicina Intensiva',
  'Medicina Interna',
  'Medicina Nuclear',
  'Nefrología',
  'Neonatología',
  'Neumología',
  'Neurocirugía',
  'Neurología',
  'Nutrición y Dietética',
  'Odontología',
  'Oftalmología',
  'Oncología',
  'Ortopedia y Traumatología',
  'Otorrinolaringología',
  'Patología',
  'Pediatría',
  'Podología',
  'Proctología',
  'Psicología',
  'Psiquiatría',
  'Radiología',
  'Rehabilitación',
  'Reumatología',
  'Urología',
];

export const INSURANCES = [
  'Sanitas',
  'Adeslas',
  'Mapfre',
  'Asisa',
  'DKV',
  'Caser',
  'AXA'
];
